version: "3"

services:
  frontend: 
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    
  ar-frontend:
    build:
      context: ./ar-frontend
      dockerfile: Dockerfile
    volumes:
      - ./ar-frontend:/ar-frontend
      - /ar-frontend/node_modules
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]
